version: 1.10.{build}
image: Visual Studio 2019
before_build:
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - Any CPU
  - x86
  - x64
build:
  project: eduJSON.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)
