version: 1.1.{build}
image: Visual Studio 2019
before_build:
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
build:
  project: eduJSON.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)\eduJSON.dll
  - path: bin\$(configuration)\$(platform)\eduJSON.pdb
  - path: bin\$(configuration)\$(platform)\ar\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\de\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\fr\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\nl\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\sl\eduJSON.resources.dll
  - path: bin\$(configuration)\$(platform)\uk\eduJSON.resources.dll
